import delayError from "./delay.js"

async function errorNotCaught() {
    try {
        return await delayError(1000);
        // We add Await to catch locally any error generated by delayError that produces the value that we want to return to the caller
    } catch (err) {
        console.error('Error caught by the async function: ' +
            err.message)
    }
}
errorNotCaught()
    .catch(err => console.error('Error caught by the caller: ' +
        err.message))